name: Build, Test and Deploy React Application

on:
  push:
    branches: [ master ]  # Assure-toi que c'est bien la bonne branche
  pull_request:
    branches: [ master ]

jobs:
  build_test:
    permissions:
      contents: write
      pull-requests: write
      actions: write
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]  # Version plus stable

    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Installer les dépendances
        run: npm ci  # Plus rapide que npm install

      - name: Build et Test
        run: |
          npm run build --if-present
          npm test

      - name: Générer version
        run: |
          npm i -g semver
          echo "GITHUB_VERSION_BUILD=$(semver 0.1.1 -i prerelease)" >> $GITHUB_ENV

      - name: Mise à jour du versioning
        run: |
          git config --global user.email "mickael.djegherif@outlook.fr"
          git config --global user.name "Mike"
          npm version ${{env.GITHUB_VERSION_BUILD}}
          echo ${{env.GITHUB_VERSION_BUILD}} >> README.md
          git commit -am "new version ${{env.GITHUB_VERSION_BUILD}}"
          git push origin HEAD:main  # Ajout du push

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
          slug: MikeXXI/pp-test-integration

      - name: Générer JSDoc
        run: npm run jsdoc

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: build
          if-no-files-found: error

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}  # Correction ici
    runs-on: ubuntu-latest
    needs: build_test

    permissions:
      pages: write
      id-token: write

    steps:
      - name: Deploy to GitHub Pages
        id: deployment  # Ajout de l'ID
        uses: actions/deploy-pages@v2
