name: Build and Test React Application
# Control when the action will run
on:
# Triggers the workflow on push or pull request events but only the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
# A workflow run is made up of one or more jobs that can run sequentially or parallely
jobs:
  build-test:
    name: deploy test
    #The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    strategy: 
      #The type of runner that the job will run on
      matrix:
        node-version : [21.x]
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm ci, build and test
        run: |
          npm ci
          npm run build --if-present
          npm test
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      - name: Generate jsdoc
        run: npm run jsdoc
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v3
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          # Upload entire repository
          path: build
          if-no-files-found: error
  
    # Deploy Job
  deploy:
    # Deploy to the GitHub Pages environnement
    environment: 
      name: gitHub-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
  # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write
      id-token: write
  # Specify runner + deployment step
    steps:
     - name: Deploy to GitHub Pages
       id: deployment
       uses: actions/deploy-pages@v2

    
    
